- name: Install dependencies
  ansible.builtin.apt:
    name:
      - cmake
      - gettext

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"

- name: Build neovim
  ansible.builtin.shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"

- name: Install neovim
  ansible.builtin.shell: "cd {{ lookup('env', 'HOME') }}/neovim && sudo make install"
