- name: Install dependencies
  ansible.builtin.apt:
    name:
      - cmake
      - gettext

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: ~/neovim

- name: Build and install Neovim
  ansible.builtin.shell: |
    cd ~/neovim
    make -j 20
    sudo make install
    rm -R ~/neovim
